### ISSUE TITLE
Bump LXML to 4.0.0

### ISSUE THREAD

**Issue by PonteIneptique** [Exirel/python-xmlunittest#12]
Hi there,
It would be great to bump lxml covered version to 4.0.0. It was released this week-end. I can do the PR if necessary, just need a go ;)

**Comment by hsmett** [comment]
Hello!
Got this error while pip installing
`xmlunittest 0.4.0 has requirement lxml<4.0.0,>=2.3, but you'll have lxml 4.2.1 which is incompatible.`
Is there any reason why we restrict lxml<4.0 here?

**Comment by hsmett** [comment]
Thank you very much!

**Comment by Exirel** [comment]
Tox says it's fine now:

```
  py27-lxml30: commands succeeded
  py27-lxml34: commands succeeded
  py27-lxml35: commands succeeded
  py27-lxml36: commands succeeded
  py27-lxml4x: commands succeeded
  py35-lxml30: commands succeeded
  py35-lxml34: commands succeeded
  py35-lxml35: commands succeeded
  py35-lxml36: commands succeeded
  py35-lxml4.x: commands succeeded
  congratulations :)
```

Tag & upload on pypi asap.

**Comment by Exirel** [comment]
And now it's available on pypi!

@hsmett and @PonteIneptique (if you're still watching here), let me know if it works for you now.

Sorry for the inconvenience.

**Comment by hsmett** [comment]
Seems good to me! Thank you! :1st_place_medal:
