### ISSUE TITLE
pip install fails since release 1.0.0

### ISSUE THREAD

**Issue by psutcliffe** [Exirel/python-xmlunittest#17]
New install of release 1.0.0 via pip fails to install correctly.

Previous code running against xmlunittest 0.5.0 now fails with:
ModuleNotFoundError: No module named 'xmlunittest'

$ python3 --version
Python 3.12.3

$ python3 -m pip install xmlunittest
Collecting xmlunittest
  Using cached xmlunittest-1.0.0-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: lxml>=4.0 in ./venv/lib/python3.12/site-packages (from xmlunittest) (5.2.2)
Using cached xmlunittest-1.0.0-py3-none-any.whl (3.3 kB)
Installing collected packages: xmlunittest
Successfully installed xmlunittest-1.0.0

Result is xmlunittest-1.0.0.dist-info directory is present in site-packages but no xmlunittest.py file.

**Comment by Exirel** [comment]
Hi!

Sorry for that, that's my fault for not being cautious enough. I've fix it, with other minor fixes (for the documentation) as well.

I didn't know people still used this package, but apparently they do!

Sorry again, version 1.0.1 should be good!

Fixed by #19
